services:
  - type: web
    name: personal-learning-path-server
    runtime: node
    rootDir: ./server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free